### ISSUE TITLE
As a developer, I want to be able to run all checks that run on github actions locally, so that I won't be surprised when my PR tests fail

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#418] opened 2021-07-27 15:38 UTC
**Description**
We should incorporate the suite of tests / checks currently being run on github locally so we aren't surprised when tests fail remotely

**Solution**
* Let's potentially incorporate [nektos/act](https://github.com/nektos/act) to enable exact parity, and/or ensure we've got a readily-accessible `npm` command we can use if needbe

**Describe alternatives you've considered**
* [nektos/act](https://github.com/nektos/act) is an option, though we should see how much we can do with standard commands and/or docker to keep things more platform-independent

**Tasks**
- [ ] Go through all tests and checks currently being run as part of the `build and deploy` github action (link [here](https://github.com/usds/justice40-tool/blob/main/.github/workflows/build_deploy.yml) and make sure each of these can be run locally

**Definition of "Done"**
- All tests and checks currently being run on github can be easily run locally

**Comment by switzersc-usds** [comment] 2021-08-09 20:31
Duplicate of the dockerization tickets (in current sprint).

**Closed by switzersc-usds** 2021-08-09 20:31 UTC
