### ISSUE TITLE
Task: Implement mobile designs with updated set of breakpoint values

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#575] opened 2021-08-25 21:58 UTC
### Describe the task
 Implement mobile designs with updated set of breakpoint values

### Dependencies
(tracked in https://github.com/usds/justice40-tool/issues/268)
- Design create mobile designs for 480px and above, and below 480px, with the caveat to see if there are special cases for certain components required for 320px (i.e. if map needs special consideration for 320px)
- Product/Design/Dev - perform manual audit on real devices against our full website feature set, document any issues on mobile devices, paying special attention to 320px configuration

### Tasks
- [x] Dev - perform dev audit of front end code and determine what needs to change (should be part of 575) 
- [ ] Dev - implement mobile designs using updated breakpoint values and audit results (subtask tracked in https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/575)

**Comment by switzersc-usds** [comment] 2021-09-08 19:43
We did the audit (Vim, Katherine, Jane, Glennette) and created new issues for specific tasks to be done here. Closing this as no longer needed / duplicate of those.

**Closed by switzersc-usds** 2021-09-08 19:43 UTC
Labels: task
