### ISSUE TITLE
Update site to show Excel file inclusion in download packet

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#291] opened 2021-07-01 20:34 UTC
**Description**
Need design for how CBG list in both .csv and .xlsx forms would be downloaded as part of a packet

Front end changes:
- change language to include excel
- make sure download button is in all the right places

**Solution**
A clear and concise description of the solution.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**
 - [ ] Design mockup of packet download link/s that shows ability to download list in both .csv and .xlsx forms along with PDF as part of .zip/s file/s

**Definition of "Done"**

**Comment by katherinedm-usds** [comment] 2021-07-08 22:34
**Description**
Need design for how CBG list in both .csv and .xlsx forms would be downloaded as part of a packet

**Solution**
A clear and concise description of the solution.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**
 - [ ] Design mockup of packet download link/s that shows ability to download list in both .csv and .xlsx forms along with PDF as part of .zip/s file/s

**Definition of "Done"**

**Comment by katherinedm-usds** [comment] 2021-07-09 20:53
I think where we landed is that it should just be one .zip, action here is just for Design to confirm the right designs for dev to reference

**Comment by katherinedm-usds** [comment] 2021-07-12 16:35
@KameronKerger @janelien can you confirm and provide pointer to the design mockup showing that we just want to do one .zip file that contains .pdf, .csv, and .xlsx?

**Comment by janelien** [comment] 2021-07-12 23:31
The current plan is to only have one button that downloads a zip of all 3 files.

**Comment by switzersc-usds** [comment] 2021-07-14 19:27
Closing as a duplicate of #351

**Closed by switzersc-usds** 2021-07-14 19:27 UTC
