### ISSUE TITLE
Excel file with styling/formatting in zip download packet

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#309] opened 2021-07-08 14:39 UTC
**Description**
We want to support federal agency program officers in being able to filter, sort, and easily digest the data shown for census block groups in the community list using a nicely styled Excel spreadsheet instead of a plain old CSV. 

**Solution**
Design for styling of the .xlsx, potentially including columns to distinguish location information (state, county, CBG ID) from score information, from "bonus" indicators

**Describe alternatives you've considered**

**Links to user research or other resources**
Related card with task for column headers https://github.com/usds/justice40-tool/issues/303 

**Tasks**
 - [ ] Create .xlsx mockup showing desired column and column header styling

**Definition of "Done"**
 - [ ] .xlsx for packet is styled consistent with design mockup

**Comment by BethMattern** [comment] 2021-07-08 15:17
Test comment

**Comment by BethMattern** [comment] 2021-07-08 15:18
test comment

**Comment by katherinedm-usds** [comment] 2021-07-09 15:18
Adding Glennette as design assignee

**Comment by katherinedm-usds** [comment] 2021-07-12 19:53
Beth has shared document plus descriptions of indicators for Glennette to mockup what Excel styling could look like

**Comment by glennettec** [comment] 2021-07-14 22:34
Here is the mockup for the .xls file.
There are three tabs:

- Dataset definitions
- Score data
- Non-score data

[Screening Tool dataset download for .xls](https://app.zenhub.com/files/358242767/526e9374-7b95-411b-a5ab-a84a9eb53c25/download)

**Comment by glennettec** [comment] 2021-07-21 22:01
Updated mockup for the .xls file. Passed Excel's accessibility checker.

Four tabs:

- About the score
- Dataset definitions
- Score data
- Non-score data

[Screening Tool Datasets download](https://app.zenhub.com/files/358242767/b44d9a55-db3e-4144-962e-4aa393d7b472/download)

**Comment by esfoobar-usds** [comment] 2021-07-29 20:36
Duplicate of #303

**Comment by katherinedm-usds** [comment] 2021-08-19 16:04
this ticket is specifically around styling, .xlsx file that is now part of the download packet has readable column names in bold, but still has more formatting and explanatory tabs to be added. Adding Blocked label as this is blocked until indicators to be included are finalized. We can format and add explanatory tabs to meet Design spec as a manual step for launch.

**Closed** 2022-02-14 21:05 UTC
Labels: Blocked, data-pipeline
