### ISSUE TITLE
"Zoom in" / CBG info panel should stay below map on mobile phones at TBD breakpoint (regardless of phone orientation)

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#572] opened 2021-08-25 20:18 UTC
**Description**
"Zoom in" / CBG info panel should stay below map on mobile phones at TBD breakpoint (regardless of phone orientation)

**Current behavior**
1. Go to https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/main/en/ on iPhone 12 and Explore the tool.
2. Observe "Zoom and select a census block group to view data" panel is below the map, as expected.
3. Use multi-touch to zoom to select a CBG and observe panel with "Cumulative Index Score", etc. is still below the map, as expected.
4. Attempt steps 1-3 with iPhone XR, observe panel stays on the side, never goes below map
5. Attempt steps 1-3 with Pixel 3, observe it moves back and forth between landscape and portrait transition

**Expected behavior**
Panel staying below map regardless of mobile phone orientation is the right tradeoff between simplicity of use and implementation

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone XR and Pixel 3 were the ones where panel showed on the side instead of below
 - OS: iOS and Android 
 - Browser: Chrome and Safari

**Additional context**

**Comment by glennettec** [comment] 2021-09-01 19:43
@katherinedm-usds if i'm understanding this task correctly, you want to confirm that the CBG info panel will remain below the map in landscape mode. If that's the case, my answer would be no because landscape mode could trigger another breakpoint view.

For example, the portrait viewport for Apple iPhone X is 375 x 812 meaning that the viewport and breakpoint is < 460. The CBG info panel should go below the map. 

Switching to landscape viewport for Apple iPhone X is 812 x 375 which should trigger the viewport > 640 breakpoint. The CBG info panel should go beside the map.

**Comment by glennettec** [comment] 2021-09-01 20:32
Found this resources that list viewports for most devices. https://yesviz.com/viewport/

**Comment by switzersc-usds** [comment] 2021-09-02 18:39
closing as a duplicate of #566

**Closed by switzersc-usds** 2021-09-02 18:39 UTC
Labels: frontend, task
