### ISSUE TITLE
Research feasibility of including census tracts that aren't DACs but are surrounded on all sides by DACs

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1333] opened 2022-02-24 15:54 UTC

**Comment by emma-nechamkin** [comment] 2022-03-11 00:41
At a good discussion point!

**Comment by emma-nechamkin** [comment] 2022-03-15 02:13
I think what makes the most sense is for us to use one of the following two identification strategies:

1. 85% of tracts that touch are DACs and low income >= 50th percentile for low income (444 tracts)
2. The criteria of 1, or 85% of tracts that touch are DACs and <7.25% without high school degree (487 tracts)

These two strategies have roughly the same demographically (notebook to be pushed). I think from the perspective of administering benefits, this will get veeeery tricky. 

Below shows four columns:
1. 75 cutoff is 75% neighbors are DAC and income >=60th
2. 85 cutoff is 85% neighbors are DAC and income >=50th
3. DAC additional constraints is (2) with the added high school attainment option
We have these stats for both population weighted and tract-level averages

Here's a tract-level average
![Screen Shot 2022-03-14 at 10.08.56 PM.png](https://images.zenhubusercontent.com/61f0224dc73ca459249d1b5d/57d949a3-e22c-45f6-aee0-55dfbcdbff6c)

Here's a population weighted average
![Screen Shot 2022-03-14 at 10.09.39 PM.png](https://images.zenhubusercontent.com/61f0224dc73ca459249d1b5d/76c353a5-fc56-42a8-b90b-42de1a54b0be)

These differences seem largely like statistical noise -- I am hesitant to draw strong conclusions data-wise. To me, the issue is ultimately a policy one. Is it possible to avoid administering benefits to "donut holes", and how should we define disadvantage for donut holes?

The last point that I wanted to mention is that we could also think of this as a variable on a spectrum, where perhaps places that are near many DACs have slightly modified criteria. I think this is an interesting question, but perhaps not the highest priority. 

@BethMattern @lucasmbrown-usds I am going to close this issue out!

**Comment by emma-nechamkin** [comment] 2022-03-17 14:18
(Just before I close this out -- my plan here is to have thresholds for score N that we can set -- like "85% of neighbors" vs "75%" in the code itself.)

**Closed** 2022-03-17 14:19 UTC
Labels: Definition N
