### ISSUE TITLE
As a data set developer, I want to implement a strategy for handling null values in territories data.

### ISSUE THREAD

**Issue by lucasmbrown-usds** [usds/justice40-tool#955] opened 2021-12-02 21:55 UTC
**Description**
About 10% of the census tracts in the 4 territories Guam, Virgin Islands, American Samoa, and Northern Mariana Islands are missing data from decennial census. Decide on strategy for how to handle these tracts.

**Comment by ahlusar1989** [comment] 2021-12-03 12:45
@lucasmbrown-usds This [document](https://www.census.gov/programs-surveys/cps/technical-documentation/methodology/imputation-of-unreported-data-items.html) may be of some help.

**Comment by vim-usds** [comment] 2022-06-01 20:58
@lucasmbrown-usds - adding this as a data thing as the front-end handles this with a special icon now.

**Comment by BethMattern** [comment] 2022-06-02 15:16
Duplicate of 1549

**Closed by BethMattern** 2022-06-02 15:16 UTC
Labels: data, data-pipeline
