### ISSUE TITLE
Compress CSV to Zip file for download packet

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#419] opened 2021-07-27 15:44 UTC
**Description**
For the front end download packet feature, we need the CSV to live as a compressed ZIP on S3. We will then add the Excel file and PDF to the ZIP as separate issues.

**Tasks**
- [ ] Update file on S3 to ZIP
- [ ] Double check that the front end has the right URL for the ZIP

**Comment by esfoobar-usds** [comment] 2021-07-29 20:34
Duplicate of #303

**Closed by esfoobar-usds** 2021-07-29 20:34 UTC
Labels: data-pipeline
